stages:
  - test
  - cleanup
  
staging: 
   stage: test
   script:
    - docker build -t ajhanna/website .
    - docker run -d --name test_container"$(date +'%d-%m-%Y')" -p  80:80 ajhanna/website 
    - curl localhost:80
    - curl localhost:80/Documentation/
    
staging:
    stage: cleanup
    script: 
     - docker stop test_container"$(date +'%d-%m-%Y')"