stages:
  - build
  - test
  - deploy
  - cleanup
  
build-web-container: 
   stage: build
   script:
    - docker build -t ajhanna/website .
    - docker run -d --name test_container"$(date +'%d-%m-%Y-%H%M')" -p  80:80 ajhanna/website 
    
test-containers-available:
    stage: test
    script:    
    - curl --fail localhost:80
    - curl --fail localhost:80/Documentation/

deploy_with_ansible:
  stage: deploy
  script:
   - ansible-playbook /home/anthonyhanna/Projects/ansible/playbooks/update.yml
   - ansible-playbook /home/anthonyhanna/Projects/ansible/playbooks/deploy-website.yml
  only: 
   - master
    
cleanup:
    stage: cleanup
    script: 
     - docker stop test_container"$(date +'%d-%m-%Y-%H%M')"