before_script:
  - eval $(ssh-agent -s)
  - whoami
  - ssh-add /var/lib/gitlab-runner/.ssh/gitlab-runner

  
stages:
  - build
  - test
  - deploy
  - cleanup
  
  
build-web-container: 
   stage: build
   script:
    - docker build -t ajhanna/website .
    - docker run -d --rm --name test_container"$(date +'%d-%m-%Y-%H%M')" -p  80:80 ajhanna/website 
    
test-containers-available:
    stage: test
    script:    
    - curl --fail localhost:80
    - curl --fail localhost:80/Documentation/

deploy_with_ansible:
  stage: deploy
  script:
   - ansible-playbook ./ansible-playbooks/update.yaml --user anthonyhanna
   - ansible-playbook ./ansible-playbooks/deploy-website.yaml --user anthonyhanna

  only: 
   - master
    
cleanup:
    stage: cleanup
    script: 
     - docker stop $(docker ps -aq)
    rules:
     - when: always