image: busybox

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - busybox-dind

before_script:
  - docker info
  tags: web

build:
  stage: build
  script:
    - docker build -t ajhanna/website .
  tags: web
   