name: Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: ["type: feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are we solving?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the desired implementation.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Technical, security, or deployment constraints.
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define what success looks like.
    validations:
      required: true
