name: Bug Report
description: Report a defect in the system
title: "[BUG] "
labels: ["type: bug"]
body:
  - type: textarea
    id: observed
    attributes:
      label: Observed Behavior
      description: What is happening?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Include logs or screenshots if applicable.
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define how this bug will be considered fixed.
    validations:
      required: true
